Update grocery-shop

diff --git a/bamboo/local/bin/go b/bamboo/local/bin/go
--- a/bamboo/local/bin/go
+++ b/bamboo/local/bin/go
@@ -1,5 +1,7 @@
 #!/bin/bash
 
+# 请在本地添加相应数据
+. /data/shell/data.sh
 
 # 日志解析服务器，data目录权限
 log()
@@ -12,36 +14,31 @@ llog()
     ssh root@192.168.51.130
 }
 
-
-server()
-{
-    # test2
-    ssh root@192.168.199.156
-}
-
-
-client()
-{
-    # test1
-    ssh root@192.168.199.155
-}
-
-s14()
-{
-    ssh root@192.168.199.14
-}
-
 homepc()
 {
     ssh silent@192.168.31.103
 }
 
+server()
+{
+    ssh ${SERVER_NAME}
+}
+
+db()
+{
+    ps -ef|grep 3359|grep -v grep|gawk '{print $2}'|xargs kill -9
+    if [[ $? != 0 ]];then
+        echo "Kill process failed."
+        exit 1
+    fi
+    ssh -L ${LOCAL_PORT}:127.0.0.1:${REMOTE_PORT} ${SERVER_NAME} -NPCf
+}
+
 usage()
 {
     echo "Go to special machine.
-    server          go to server(test2)
-    client          go to client(test1)
-    s14             go to 192.168.199.14
+    server          go to online server
+    db              go to online mysql
     log             go to log analysis server
     llog            go to local log analysis server
     homepc          go to home pc machines
@@ -52,10 +49,8 @@ usage()
 case "$1" in
     server)
         server;;
-    client)
-        client;;
-    s14):
-        s14;;
+    db):
+        db;;
     log):
         log;;
     llog):
