Modify go script

diff --git a/bamboo/local/bin/go b/bamboo/local/bin/go
--- a/bamboo/local/bin/go
+++ b/bamboo/local/bin/go
@@ -44,6 +44,13 @@ db()
         exit 1
     fi
     ssh -L ${CO_PORT}:127.0.0.1:${REMOTE_PORT} ${COCHAT_NAME} -NPCf
+
+    ps -ef|grep ${WX_PORT}| grep -v grep|gawk '{print $2}'|xargs kill -9
+    if [[ $? != 0 ]];then
+        echo "Kill process failed."
+        exit 1
+    fi
+    ssh -L ${WX_PORT}:127.0.0.1:${REMOTE_PORT} ${WX_NAME} -NPCf
 }
 
 usage()
